---
- name: Deploy DEV Agent
  hosts: k3s_managers
  run_once: true
  become: true
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
    K8S_AUTH_NO_PROXY: "{{ no_proxy }}"
  roles:
    - agent
