---
- name: Install Docker
  hosts: docker
  become: true
  roles:
    - docker

- name: Deploy DEV Agent
  hosts: k3s_managers
  run_once: true
  become: true
  environment:
    KUBECONFIG: "{{ kube_config_path }}"
  roles:
    - deploy