---
- name: Uninstall docker
  hosts:
    - docker
  become: true
  tasks:
    - name: Stop and disable Docker
      ansible.builtin.systemd:
        name: docker
        enabled: false
        state: stopped

    - name: Remove Docker configuration directory
      ansible.builtin.file:
        name: /etc/systemd/system/docker.service.d
        state: absent

    - name: Uninstall python module
      ansible.builtin.pip:
        name: docker
        state: absent

    - name: Uninstall Docker
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: absent
        autoremove: true
