---
- name: Delete Deployment
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "{{ agent_stateful_set_name }}"
        namespace: "devops"
