name: Ubi Agent Build and Push
description: Build and push Ubi Agent Docker image
inputs:
  actions_version:
    description: GitHub Actions version
    required: true
  targetarch:
    description: Target architecture
    required: true
  actions_tar_destination:
    description: Destination path to save the downloaded actions tar file
    required: true
  tag:
    description: Tag to publish
    required: true
  platform:
    description: Platform to build
    required: true
runs:
  using: composite
  steps:
    - name: Download agent file
      uses: espresso-software/actions/common/download-file@feature/docker-actions
      with:
        url: https://github.com/actions/runner/releases/download/v${{ inputs.actions_version }}/actions-runner-${{ inputs.targetarch }}-${{ inputs.actions_version }}.tar.gz
        destination: ${{ inputs.actions_tar_destination }}

    - name: Publish Docker Image
      uses: espresso-software/actions/docker/build-and-push@feature/docker-actions
      with:
        repository: ${{ env.DOCKER_REPOSITORY }}
        tag: ${{ inputs.tag }}
        build_dir: ubi-agent