# This is a basic workflow to help you get started with Actions

name: Docker Self Heal
permissions:
  contents: read
  pull-requests: read
  issues: write

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  docker-self-heal:
    runs-on:
      - self-hosted
      - ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - name: Install docker
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: docker.yml
          inventory_path: inventory/hosts.ini