# This is a basic workflow to help you get started with Actions

name: Ubi Agent Build and Deploy

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
    paths:
      - ubi-agent/**
      - .github/workflows/ubi-agent.yml
      - .github/actions/ubi-agent-build/**
  pull_request:
    branches:
      - main
    paths:
      - ubi-agent/**
      - ubi-agent.yml
      - .github/workflows/ubi-agent.yml
      - .github/actions/ubi-agent-build/**
      - roles/uat-deploy/**
  schedule:
    - cron: '0 12 * * 5'

env:
  DOCKER_REPOSITORY: coffee206/github-actions
  GITHUB_ACTIONS_VERSION: '2.321.0'
  BUILD_DIR: ubi-agent

jobs:
  versioning:
    runs-on:
      - self-hosted
      - docker
    
    steps:
      - uses: actions/checkout@v2
      #TODO: Versioning
  
  arm64-build:
    needs:
      - versioning
    runs-on:
      - self-hosted
      - docker
      - ARM64
    env:
      TARGETARCH: linux-arm64
  
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish image
        uses: ./.github/actions/ubi-agent-build
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
        with:
          actions_version: ${{ env.GITHUB_ACTIONS_VERSION }}
          targetarch: ${{ env.TARGETARCH }}
          build_directory: ${{ env.BUILD_DIR }}
          tag: arm64-develop-${{ github.run_number }}
  
  x64-build:
    # if: github.event.pull_request || github.event_name == 'schedule'
    needs:
      - versioning
    runs-on:
      - self-hosted
      - docker
      - x64
    
    env:
      TARGETARCH: linux-x64
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and publish image
        uses: ./.github/actions/ubi-agent-build
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
        with:
          actions_version: ${{ env.GITHUB_ACTIONS_VERSION }}
          targetarch: ${{ env.TARGETARCH }}
          build_directory: ${{ env.BUILD_DIR }}
          tag: x64-develop-${{ github.run_number }}

  deploy:
    needs: 
      - arm64-build
      - x64-build
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v2
      - uses: espresso-software/actions/ansible/run-playbook@feature/docker-actions
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: ubi-agent.yml
          inventory_path: inventory/hosts.ini
          vars: tag=arm64-develop-${{ github.run_number }}
  
  promote:
    needs: 
      - deploy
    runs-on:
      - self-hosted
      - docker
    steps:
      - name: Promote x64 image
        uses: espresso-software/actions/docker/promote@feature/docker-actions
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          old_tag: x64-develop-${{ github.run_number }}
          promote_tag: x64-${{ github.run_number }}
          promote_latest: 'true'
          promote_custom_latest: x64-latest
      
      - name: Promote arm64 image
        uses: espresso-software/actions/docker/promote@feature/docker-actions
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          old_tag: x64-develop-${{ github.run_number }}
          promote_tag: arm64-${{ github.run_number }}
          promote_latest: 'true'
          promote_custom_latest: arm64-latest
      
      - name: Create latest manifest
        uses: espresso-software/actions/docker/common-tag@feature/docker-actions
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          tag: latest
          x64_tag: x64-latest
          arm64_tag: arm64-latest
      
      - name: Create release manifest
        uses: espresso-software/actions/docker/common-tag@feature/docker-actions
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          tag: release
          x64_tag: x64-${{ github.run_number }}
          arm64_tag: arm64-${{ github.run_number }}
      
    
        

        
        