# This is a basic workflow to help you get started with Actions

name: Ubi Agent Development Build

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
    paths:
      - ubi-agent/**
      - .github/workflows/ubi-agent-development.yml
  pull_request:
    branches:
      - main
    paths:
      - ubi-agent/**
      - .github/workflows/ubi-agent-development.yml

env:
  DOCKER_REPOSITORY: coffee206/github-actions
  GITHUB_ACTIONS_VERSION: '2.321.0'
  BUILD_DIR: ubi-agent

jobs:
  #TODO: Versioning
  arm64-build:
    runs-on:
      - self-hosted
      - docker
      - ARM64
    env:
      TARGETARCH: linux-arm64
  
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish image
        uses: ./.github/actions/ubi-agent-build
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
        with:
          actions_version: ${{ env.GITHUB_ACTIONS_VERSION }}
          targetarch: ${{ env.TARGETARCH }}
          build_directory: ${{ env.BUILD_DIR }}
          tag: arm64-develop-${{ github.run_number }}
          platform: ${{ runner.os }}
  
  x64-build:
    if: github.event.pull_request
    runs-on:
      - self-hosted
      - docker
      - x64
    
    env:
      TARGETARCH: linux-x64
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and publish image
        uses: ./.github/actions/ubi-agent-build
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
        with:
          actions_version: ${{ env.GITHUB_ACTIONS_VERSION }}
          targetarch: ${{ env.TARGETARCH }}
          build_directory: ${{ env.BUILD_DIR }}
          tag: x64-develop-${{ github.run_number }}
          platform: ${{ runner.os }}
  
  
      
    
        

        
        